# main text of home
title: Vishwesh Jainkuniya
bio: curious mind

# twitter summary info
description: My personal corner

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/2017-02-09-17-44-10-227.jpg

# your site color theme, true for dark theme,
# false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: /assets/vishwesh-cv.pdf

url: https://jainkuniya.github.io
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-104769451-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: jainkuniya # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: jainkuniya
twitter: jainkuniya
# google: mygoogle
instagram: jainkuniya
# pinterest: mypinterest
linkedin: jainkuniya
youtube: botlatexx3661
# spotify: myspotify
# lastfm: mylastfm
github: jainkuniya
stackoverflow: 5612089/vishwesh-jainkuniya
# quora: userquora
# reddit: username
medium: jainkuniya
# vimeo: myvimeo
# lanyrd: mylanyrd
email: jainkuniya@gmail.com

authors:
  vishwesh:
    name: Vishwesh Jainkuniya
    bio: Learner
    external-image: false
    picture: assets/images/2017-02-09-17-44-10-227.jpg
    twitter: jainkuniya

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
  base_url: https://github.com/

portfolio:
  music:
    - link: https://www.instagram.com/reel/Cn5D4x2gXh5/
    - link: https://www.instagram.com/reel/CqGTEIlg1AT/
  talks:
    - logo: /assets/portfolio/reactindia.jpeg
      name: React India
      link: https://www.reactindia.io/speakers/vishwesh-jainkuniya
      slides: https://twitter.com/jainkuniya/status/1572942681302761472?s=20&t=UovBQe6BasAWpD9yTKz0RA
      title: Building loader free online apps
  companies:
    - logo: /assets/portfolio/eka.webp
      name: eka.care
      link: https://eka.care
      designation: Lead Engineer
    - logo: /assets/portfolio/predictgrowth.png
      name: Predict Growth
      link: https://predictgrowth.ai
      designation: Tech Adviser
    - logo: /assets/portfolio/beeceptor.png
      name: Beeceptor
      link: https://beeceptor.com
      designation: Product & Tech Adviser    
    - logo: /assets/portfolio/gojek.png
      name: GoJek (GoTo)
      link: https://goto.com
      designation: Product Engineer
    - logo: /assets/portfolio/tealfeed.png
      name: Tealfeed
      link: https://tealfeed.com
      designation: Tech Adviser & Mentor
    - logo: /assets/portfolio/renderpdf.svg
      name: RenderPDF
      link: https://tealfeed.com
      designation: Product Adviser
    - logo: /assets/portfolio/zulip.png
      name: Zulip
      link: https://zulip.org
      designation: Mobile enginner
    - logo: /assets/portfolio/facebook.webp
      name: RN @ Facebook
      link: https://zulip.org
      designation: Open source contributor
    - logo: /assets/portfolio/gsoc.png
      name: Google Summer of Code
      link: https://summerofcode.withgoogle.com/
      designation: Mentor
    - logo: /assets/portfolio/mrhot.png
      name: Mr Hot
      link: https://www.crunchbase.com/organization/mr-hot-foods
      designation: Full Stack Developer
    - logo: /assets/portfolio/liveunite.jpeg
      name: Liveunite
      link: https://jainkuniya.github.io/project-liveunite/
      designation: Full Stack Developer