# For local testing, run:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
url: http://localhost:4000

# To enable google analytics, supply your token below
analytics-google: "UA-10fdasdsa4769451-1"
